### ISSUE TITLE
Time bomb?

### ISSUE THREAD

**Issue by Javadad01** [flyboy013/DEF_Sensor_Emulator_Firmware#1]
I love the work, super freakin' AWESOME!!! To keep out of trouble with the regulators, I would suggest a 16 hour-ish time bomb in the software. That way it can be classified as emergency use only. Otherwise the software would let the end user run without the proper safeties in place forever. When it goes off, the end user just reflashes and they're off and running in 20 minutes or less. Just FYI, this project bypasses several checks and safeties. If the end user tries to cheat the system, they risk costly damage to the SCR system and vehicle.

**Comment by flyboy013** [comment]
The simulator was designed to allow motorhome owners to safely continue driving the coach following a DEF head failure.  It would allow them to avoid an unsafe 5 mph derate.  Given that replacement part availability is currently being quoted as up to a month or more, this would allow an individual to continue their current trip and return home for local repair when the part is available.  

The device simulates values for temperature, quantity, and quality.  If for some reason the tank ran dry, the DEF pump would sense this and an appropriate fault code would be generated.  The simulator does not simulate data for any other emissions component.  If the quality of the fluid was deluited, the SCR sensors would pick up on this as the exhaust gases would out of range.  I believe the only possible uncaught error would be if the DEF temperature was too high (due to coolant valve failure) or too cold due to operating in freezing temperatures which motorhomes typically avoid.  So why there is a chance of something going wrong, it's unlikely and something we suggest the vehicle owners monitor when using such a device.

**Comment by Javadad01** [comment]
And how many times would the quality codes reset because someone put diesel
or E85 in the def tank by accident? I was working on these things long
before the def quality sensor in the tank was a requirement. I've seen the
damage and had to fix what I could. I remember when Navistar sued the other
manufacturers because they didn't comply to the letter of the law. A
freightliner could run out of DEF, and as long as you didn't cycle the
ignition, you could keep fueling and run indefinitely. The situation above
is a prime example. The engine software will catch it as long as everything
is working properly, but the system will still incur damage. And now not
under warranty or possibly insurance coverage. The in tank quality sensor
was step to help alleviate the damage from the 10%.

I appreciate what you have put forth and accomplished. But you're exposing
yourself to a lot of potential liability. The feds didn't go after the
people who bought and installed all the delete kits, they went after the
source. At $50,000 per infraction of the CAA, even as a good Samaritan, it
is still a lot.

I'm sure you've heard some different versions judging by your website and
your response to me. I'll go back on and mark it closed or you can remove
it if you wish. It was just the easiest way to get your attention.

Thank you again for the effort and product.

Sam White
