### ISSUE TITLE
Releasing the source code

### ISSUE THREAD

**Issue by nshanny** [flyboy013/DEF_Sensor_Emulator_Firmware#2]
Hi there, 

Would it be possible for you to open source the underlying code in addition to the compiled hex code? I would like to see exactly what it is doing before plugging into my M2-106.  I would also like to port it to the Rasp-PI. 

Thanks
Nick Shanny

**Comment by linuxkidd** [comment]
Agreed, it'd be great to have the option to cross compile this or use it as the base for other ports since parts availability is scarce for the exact pieces referenced / compiled for.

Thanks for all your work on this!

**Comment by cterwilliger** [comment]
Yes, please. It can only be a good thing for the project going forward. Thank you for the work so far. Very professional presentation.

**Comment by flyboy013** [comment]
The DEF Sensor Simulator was developed by a team of individuals and the question was presented to the team about releasing the source code.   Given the potential for the software to be utilized to implement an emissions “delete” capability, the majority of the individuals felt that it would be best to not release the source code.  So, at this time, I feel compelled to respect the wishes of the team and not release the source code.

**Comment by linuxkidd** [comment]
@flyboy013 I respect your decision, it is yours to make.

  My counter argument to the 'emissions delete' worry is -- those who are determined to do something bad, will always find a way.   As an example, VPNs are great since they protect people from bad actors online, but they also allow bad actors to be protected from snooping of traffic from law enforcement.  Should VPNs not be available due to the risk of bad actors?  Clearly, the benefits out weigh the risk with VPNs.
  
  IMO, the decision to open, or not open source the DEF simulator should be weighed similarly - does the benefit ( cross compiling for broader access based on parts availability, people feeling more comfortable with the code running in their rig, potential code optimizations, unpredictable other amazing projects, etc ) out weigh the risk of someone using it to DEF delete?

Thanks again to the team for all the work.  Even if my argument above doesn't convince the devs to release the code, the project is greatly appreciated.

**Comment by flyboy013** [comment]
For what it's worth, I was arguing for releasing it, but that is not what the team as a whole wanted.    My arguments included some of the points you brought up.

**Comment by nshanny** [comment]
Thanks.  With the chip shortage it is becoming difficult to obtain the hardware required. I just happen to have a RaspPI with canbus laying around.

Cheers
Nick

________________________________

**Comment by flyboy013** [comment]
There’s been some talk about a potential need for a RPi version but frankly I don’t think it’s worth the effort.   First off, the majority of the software would have to be rewritten.  Then there’s the fact that a Linux OS would be difficult for most of the RV owners.  To do things right the OS would need to be rebuilt to include the J1939 support.   It would be easier to acquire some AVR based Arduino (plenty of models) and add a $5 Chinese CAN module.  I believe the HW supply would be better and the components cheaper.  It just requires a little more work for a user to assemble.  Perhaps a breadboard with some jumper wires too.

**Comment by linuxkidd** [comment]
I have a decent amount of CAN bus experience ( started CAN bus hacking in 2005, created Coachproxy, wrote my Astronomy Shed roll-off-roof control using CAN bus, etc.. )  J1939 is just another message encoding that rides on CAN bus.  The Pi OS has support for SPI connected CAN bus ( mcp2515, etc ) with socketcan handling which makes that part very easy, especially compared to Arduino / C coding the stack ( which I've done too ).  Although, I do agree it's cheaper and easier for most owners to use Arduino+cheap CAN board.

Instead of open sourcing the project, would it be possible to get the rest of the PGN's that are used ( you referenced as overhead PGNs ) or CAN protocol specific messages and timings?  (honestly, this will only save me a bit of time in producing similar functioning code).

**Comment by cterwilliger** [comment]
Well, there are many RPi options available.  Pi zeros are available for less than $20 and include WiFi which leads to some interesting monitoring capability.  Loading the software is no more difficult for novice users than what you're doing now with avrdude.  Rewriting the software for RPi is trivial for those of us with experience which is exactly why we're asking for source access.
