### ISSUE TITLE
CS on Pin 10?

### ISSUE THREAD

**Issue by hfb3** [flyboy013/DEF_Sensor_Emulator_Firmware#5]
Is there any way to get the firmware compiled with CS connected to pin 9 instead of pin 10?  
I have several Can-Bus V1.2 boards that DO NOT have the selection pads on the back of the 
board.

Harry

**Comment by flyboy013** [comment]
Which platform (Due, Uno, etc) would you need it for?

**Comment by hfb3** [comment]
Uno

**Comment by flyboy013** [comment]
The code is currently using pin 9 for SPI CS.

```
#if defined(ARDUINO_AVR_LEONARDO)
  const int SPI_CS_PIN = 17;    // This is for the Seeed CanBed board using atmega32U4 chip
#else
  const int SPI_CS_PIN = 9;     // This is for UNO/ATMega using Seeed CAN shield V2.0
#endif
```

**Comment by hfb3** [comment]
My bad.  I mixed up the pins when I was looking at the specs..  I should have requested Pin 10 and not Pin 9.

const int SPI_CS_PIN = 10;

**Comment by hfb3** [comment]
https://www.cytron.io/p-elecfreaks-can-bus-shield

You can clearly see the trace going to pin 10.

Thanks

**Comment by flyboy013** [comment]
I have updated the code to use pin 10.  The attached zip file contains the hex file to load onto the Uno.  The baseline has not been updated and since your HW deviates from the recommended configuration I'm unable to provide any support.  We have not tested with the HW you are using.

[DEF_Sensor_Emulator_CS10.ino.standard.hex.zip](https://github.com/flyboy013/DEF_Sensor_Emulator_Firmware/files/8098733/DEF_Sensor_Emulator_CS10.ino.standard.hex.zip)

**Comment by flyboy013** [comment]
Issue title updated to reflect request to use pin 10 (not 9) for CS.

**Comment by hfb3** [comment]
That is fine.  I will test it and post an update once done.

Thank you very much.

**Comment by hfb3** [comment]
Worked like a charm.

Thanks

Harry
